"""empty message

Revision ID: 0e1a902d337d
Revises: 619889dc1779
Create Date: 2025-02-26 23:55:45.609538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1a902d337d'
down_revision = '619889dc1779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('coin', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('balance'),
    sa.UniqueConstraint('coin'),
    sa.UniqueConstraint('type')
    )
    op.create_table('account_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accounts_id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('date', sa.String(length=80), nullable=False),
    sa.Column('time', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['accounts_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amount'),
    sa.UniqueConstraint('coin'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('time'),
    sa.UniqueConstraint('type')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('birthdate', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['birthdate'])
        batch_op.create_unique_constraint(None, ['first_name'])
        batch_op.create_unique_constraint(None, ['country'])
        batch_op.create_unique_constraint(None, ['last_name'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('country')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.drop_table('account_details')
    op.drop_table('accounts')
    # ### end Alembic commands ###
